spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aistock?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:aistock}
    password: ${DB_PASSWORD:aistock}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    com.TeamFP.aistock: debug
